### ISSUE TITLE
Module build failed: Error: .sourceMap is an alias for .sourceMaps, cannot use both

### ISSUE THREAD

**Issue by pwalczyszyn** [adobe/react-twist#19]
### Actual behavior

Build fails when current project has beta version of Babel 7 configured in package.json. 

Twist Version: 0.1.2
Node Version: 8.9.4
NPM Version: 5.6.0
Operating System and Version: OSX High Sierra
Babel version: 7.0.0-beta.40

This is the stack trace I'm seeing:
```
at assertNoDuplicateSourcemap (/Users/pwalczys/Projects/my-project/node_modules/@babel/core/lib/config/validation/options.js:107:11)
    at validate (/Users/pwalczys/Projects/my-project/node_modules/@babel/core/lib/config/validation/options.js:60:3)
    at loadConfig (/Users/pwalczys/Projects/my-project/node_modules/@babel/core/lib/config/index.js:37:48)
    at transformSync (/Users/pwalczys/Projects/my-project/node_modules/@babel/core/lib/transform-sync.js:13:36)
    at Object.transform (/Users/pwalczys/Projects/my-project/node_modules/@babel/core/lib/transform.js:20:65)
    at transpile (/Users/pwalczys/Projects/my-project/node_modules/babel-loader/lib/index.js:55:20)
    at Object.module.exports (/Users/pwalczys/Projects/my-project/node_modules/babel-loader/lib/index.js:179:20)
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server app/renderer.js
```

**Comment by joekukish** [comment]
@lanther It seems like the plugins are not compatible with babel@7.0.0-beta.40
